seed: 42
paths:
  raw_data: data/raw/churn.csv
  processed_data: data/processed/churn_processed.csv
  model_dir: models
  model_file: models/xgb_churn.pkl
model:
  xgboost:
    n_estimators: 300
    learning_rate: 0.05
    max_depth: 5
    subsample: 0.9
    colsample_bytree: 0.9
    reg_lambda: 1.0
    reg_alpha: 0.0
    random_state: 42
    tree_method: auto
target: churn
test_size: 0.2
positive_class: 1

